version: '3'

services:
#  front-end:
#    container_name: front-end
#    build:
#      context: .
#      dockerfile: ./front-end/Dockerfile
#    networks:
#      - app

  back-end:
    container_name: back-end
    build: ./back-end
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '5000'
    volumes:
      - dist:/dist
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - app

  front-end:
    container_name: front-end
    build: ./front-end
    volumes:
      - dist:/app/build
    networks:
      - app

volumes:
  dist:

networks:
    app:
      driver: bridge
